### ISSUE TITLE
Uncaught SyntaxError: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by Caffa** [paradoxxxzero/atom-python-import-magic#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [python-import-magic](https://github.com/paradoxxxzero/atom-python-import-magic) package 0.11.0

### Stack Trace

Uncaught SyntaxError: Unexpected token P in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token P in JSON at position 0
    at Object.parse (native)
    at /packages/python-import-magic/lib/proc.coffee:47:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.7.3 
autocomplete-python 1.8.62 
build 0.67.0 
build-python 0.9.1 
busy 0.7.0 
Hydrogen 1.7.0 
ipython-exec 1.2.0 
jupyter-notebook 0.0.9 
kite 0.18.0 
language-kivy 0.1.1 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.5 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
python-import-magic 0.11.0 
python-iresolve 0.0.3 
python-isort 0.0.7 
python-snippets 1.9.0 
python-tools 0.6.9 
python-yapf 0.13.0 
tool-bar-almighty 0.8.1 
wakatime 6.0.13 
```

**Comment by paradoxxxzero** [comment]
Can you please retry with the latest release (1.0.2)?
