### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by macperez** [paradoxxxzero/atom-python-import-magic#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [python-import-magic](https://github.com/paradoxxxzero/atom-python-import-magic) package 1.0.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at call (/packages/python-import-magic/lib/proc.js:43:18)
    at Object.reindex (/packages/python-import-magic/lib/python-import-magic.js:80:5)
    at /packages/python-import-magic/lib/python-import-magic.js:37:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:53.7.0 settings-view:open (input.hidden-input)
     -0:29 python-import-magic:update (input.hidden-input)
     -0:10.9.0 pane:show-next-item (input.hidden-input)
     -0:06.2.0 pane:show-previous-item (div.package-detail.panels-item)
     -0:03.7.0 python-import-magic:reindex (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.8.61 
python-autopep8 0.1.3 
python-import-magic 1.0.3 
python-tools 0.6.9 
seti-icons 1.4.3 
```

**Comment by paradoxxxzero** [comment]
Strange, seems like a permission issue with your python executable.
What's your 'python executable paths' setting?
